name: Azure Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up SSH connection to Azure server
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up SSH connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: SSH into Azure server and pull code
        run: |
          ssh -i ~/.ssh/id_rsa azureuser@20.25.181.110 "echo hello world"

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Touch SSH directory
        run:  mkdir $HOME/.ssh

      - name: Configure SSH known hosts
        run: ssh-keyscan -H 20.25.181.110 >> $HOME/.ssh/known_hosts
      
      - name: SSH to Azure server and pull repository
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} -o StrictHostKeyChecking=no azureuser@20.25.181.110  'echo hello world'

      - name: Build Docker image
        run: |
          docker build -t frontend:$(date +%Y%m%d%H%M%S) .

      - name: Check if port 3000 is available
        run: |
          if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null; then
            echo "Port 3000 is already in use."
          else
            docker run -p 3000:3000 frontend:$(date +%Y%m%d%H%M%S)
          fi

      - name: Check if port 3001 is available
        run: |
          if lsof -Pi :3001 -sTCP:LISTEN -t >/dev/null; then
            echo "Port 3001 is already in use."
          else
            docker run -p 3001:3001 frontend:$(date +%Y%m%d%H%M%S)
          fi
